### ISSUE TITLE
Tech Stack 

### ISSUE THREAD

**Issue by alyhoop** [NaticOrg/natic#14]
Update at tomorrow's SCRUM

**Comment by alyhoop** [comment]
To be discussed: 

- Web Technologies - JS, HTML, CSS
- Front End Framework - React, _React-Bootstrap?_
- Back End - Python, Django
- Package Manager - _yarn?_
- Container - Docker
- Version Control - GitHub, Git
- Project Management - Confluence
- Testing Framework - ?

**Comment by chaiwa-berian** [comment]
Adding these to the CONTRIBUTING file would help document the tech stack being used by the project. We can then version those sections as we go.

**Comment by alyhoop** [comment]
Okay
