### ISSUE TITLE
Create How-To for dev environment setup Wiki

### ISSUE THREAD

**Issue by vramirez209** [NaticOrg/natic#28]
Created instructions for setting up a new dev container with docker, postgres, react. By default all ports are opened and dependencies installed.

**Comment by alyhoop** [comment]
Didn't mean to put my page in front of yours, but added a "get the front end running page to the wiki" folder.

**Comment by vramirez209** [comment]
Added two wiki pages. 

Setup instructions - [Link](https://github.com/NaticOrg/natic/wiki/How-To:-Setting-up-a-Unix-dev-environment)

Environment overview - [Link](https://github.com/NaticOrg/natic/wiki/Environment)
